spring:
  datasource:
    name: YPTPDB2
    url: jdbc:oracle:thin:@172.24.114.170:1521:yptpdb2?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8
    username: cds_dev
    password: cds_123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml